Server:
   #gin配置相关
   RunMode: debug    #gin运行模式
   HttpPort: 8000    #监听端口
   ReadTimeTime: 60  #读超时时间
   WriteTimeout : 60 #写超时时间
App:
  #app服务应用相关
  DefaultPageSize: 10        #默认每页大小
  MaxPageSize: 100           #最大每页大小
  LogSavePath: storage/logs  #日志保存路径
  LogFileName: app           #日志文件名称
  LogFileExt: .log           #日志文件后缀
Database:
  #数据库配置相关
  DBType: mysql       #数据库类型
  Username: root      #用户名
  Password: root      #密码
  Host: localhost     #服务地址
  DBName: blog-service #数据库名称
  TablePrefixx: blog_ #表前缀
  Charset : utf8      #编码
  ParseTime: True     #开启时间
  MaxIdleConns: 10    #最大空闲连接数
  MaxOpenConns: 30    #最大打开连接数
Redis:
  #redis配置相关
  Network: tcp    #协议
  Addr: 127.0.0.1 #地址
  Port: 6379      #端口
  Password : ""   #密码
  DB: 0           #数据库
  
  #连接池容量及闲置连接数量
  PoolSize:     15 # 连接池最大socket连接数，默认为4倍CPU数， 4 * runtime.NumCPU
  MinIdleConns: 10 #在启动阶段创建指定数量的Idle连接，并长期维持idle状态的连接数不少于指定数量；。

  #超时
  DialTimeout:  5  #连接建立超时时间，默认5秒。
  ReadTimeout:  3  #读超时，默认3秒， -1表示取消读超时
  WriteTimeout: 3  #写超时，默认等于读超时
  PoolTimeout:  4  #当所有连接都处在繁忙状态时，客户端等待可用连接的最大等待时长，默认为读超时+1秒。

  #闲置连接检查包括IdleTimeout，MaxConnAge
  IdleCheckFrequency: 60 #闲置连接检查的周期，默认为1分钟，-1表示不做周期性检查，只在客户端获取连接时对闲置连接进行处理。
  IdleTimeout:        5  #闲置超时，默认5分钟，-1表示取消闲置超时检查
  MaxConnAge:         0   #连接存活时长，从创建开始计时，超过指定时长则关闭连接，默认为0，即不关闭存活时长较长的连接

  #命令执行失败时的重试策略
  MaxRetries:      0   # 命令执行失败时，最多重试多少次，默认为0即不重试
  MinRetryBackoff: 8   #每次计算重试间隔时间的下限，默认8毫秒，-1表示取消间隔
  MaxRetryBackoff: 512 #每次计算重试间隔时间的上限，默认512毫秒，-1表示取消间隔
