Server:
   RunMode: debug
   HttpPort: 8000
   ReadTimeTime: 60
   WriteTimeout : 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 127.0.0.1
  DBName: go-blog
  TablePrefixx: blog_
  Charset : utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
